[PHP]
date.timezone = Asia/Tokyo
default_charset = UTF-8

memory_limit = 256M
max_execution_time = 60

upload_max_filesize = 10M
post_max_size = 12M

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

[Session]
session.cookie_httponly = On
session.cookie_samesite = Lax